import { Fundamental } from '../../app/core/models/fundamental';

export const fundamentals: Array<Fundamental> = [
  {
    id: 0,
    command: 'eight forwardLength, 8-to-5',
    forwardLength: 8,
    sideLength: 0,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 1,
    command: 'eight backward, 8-to-5',
    forwardLength: -8,
    sideLength: 0,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 2,
    command: 'right oblique, 8-to-5',
    forwardLength: 8,
    sideLength: 8,
    counts: 12,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 3,
    command: 'left oblique, 8-to-5',
    forwardLength: 8,
    sideLength: -8,
    counts: 12,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 4,
    command: 'eight right horn slide',
    forwardLength: 8,
    sideLength: 0,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 5,
    command: 'eight left horn slide',
    forwardLength: 8,
    sideLength: 0,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 6,
    command: 'left flank',
    forwardLength: 0,
    sideLength: 0,
    counts: 0,
    stepSize: 8,
    facingDegreeOffset: -90,
  },
  {
    id: 7,
    command: 'right flank',
    forwardLength: 0,
    sideLength: 0,
    counts: 0,
    stepSize: 8,
    facingDegreeOffset: 90,
  },
  {
    id: 8,
    command: 'regular TTR',
    forwardLength: 0,
    sideLength: 0,
    counts: 0,
    stepSize: 8,
    facingDegreeOffset: 180,
  },
  {
    id: 9,
    command: 'box TTR',
    forwardLength: 0,
    sideLength: 0,
    counts: 4,
    stepSize: 8,
    facingDegreeOffset: -90,
  },
  {
    id: 10,
    command: 'slide TTR on 2',
    forwardLength: 8,
    sideLength: 0,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 180,
  },
  {
    id: 11,
    command: 'slide TTR on 4',
    forwardLength: 8,
    sideLength: 0,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 180,
  },
  {
    id: 12,
    command: 'slide TTR on 6',
    forwardLength: 8,
    sideLength: 0,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 180,
  },
  {
    id: 13,
    command: 'eight right lateral slide',
    forwardLength: 0,
    sideLength: 8,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 14,
    command: 'eight left lateral slide',
    forwardLength: 0,
    sideLength: -8,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 15,
    command: 'eight right backward lateral slide',
    forwardLength: 0,
    sideLength: 8,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 16,
    command: 'eight left backward lateral slide',
    forwardLength: 0,
    sideLength: -8,
    counts: 8,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 17,
    command: 'up stepSize turn TTR',
    forwardLength: 0,
    sideLength: 0,
    counts: 2,
    stepSize: 8,
    facingDegreeOffset: 180,
  },
  {
    id: 18,
    command: 'up stepSize turn to the right',
    forwardLength: 0,
    sideLength: 0,
    counts: 2,
    stepSize: 8,
    facingDegreeOffset: 90,
  },
  {
    id: 19,
    command: 'up stepSize turn to the left',
    forwardLength: 0,
    sideLength: 0,
    counts: 2,
    stepSize: 8,
    facingDegreeOffset: -90,
  },
  {
    id: 20,
    command: 'eight stepSize kicks',
    forwardLength: 8,
    sideLength: 0,
    counts: 16,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 21,
    command: 'sideLength stepSizes',
    forwardLength: 0,
    sideLength: -1,
    counts: 2,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 22,
    command: 'stepSize sideLengths',
    forwardLength: 0,
    sideLength: 1,
    counts: 2,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 23,
    command: 'eight forwardLength, 6-to-5',
    forwardLength: 8,
    sideLength: 0,
    counts: 6,
    stepSize: 6,
    facingDegreeOffset: 0,
  },
  {
    id: 24,
    command: 'eight backward, 6-to-5',
    forwardLength: -8,
    sideLength: 0,
    counts: 6,
    stepSize: 6,
    facingDegreeOffset: 0,
  },
  {
    id: 25,
    command: 'right oblique, 6-to-5',
    forwardLength: 8,
    sideLength: 8,
    counts: 8,
    stepSize: 6,
    facingDegreeOffset: 0,
  },
  {
    id: 26,
    command: 'left oblique, 6-to-5',
    forwardLength: 8,
    sideLength: -8,
    counts: 8,
    stepSize: 6,
    facingDegreeOffset: 0,
  },
  {
    id: 27,
    command: 'eight forwardLength, 10-to-5',
    forwardLength: 8,
    sideLength: 0,
    counts: 10,
    stepSize: 10,
    facingDegreeOffset: 0,
  },
  {
    id: 28,
    command: 'eight forwardLength, 12-to-5',
    forwardLength: 8,
    sideLength: 0,
    counts: 12,
    stepSize: 12,
    facingDegreeOffset: 0,
  },
  {
    id: 29,
    command: 'eight forwardLength, 16-to-5',
    forwardLength: 8,
    sideLength: 0,
    counts: 16,
    stepSize: 16,
    facingDegreeOffset: 0,
  },
  {
    id: 30,
    command: 'hats off, Ohio on the end',
    forwardLength: 0,
    sideLength: 0,
    counts: 25,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
  {
    id: 31,
    command: 'hats off, 1-2-3',
    forwardLength: 0,
    sideLength: 0,
    counts: 26,
    stepSize: 8,
    facingDegreeOffset: 0,
  },
];
